mysite/blog/urls.py
from django.urls import path
from blog.views import *


app_name = 'blog'  
urlpatterns = [
    path('', index_view, name='index'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('elements/', elements_view, name='elements'),
    path('newsletters/', newsletters_view, name='newsletters'),
    
    path('test/', test, name='test'),
]

mysite/blogpage/urls.py
from django.urls import path
from blogpage.views import *
#from django.conf import settings
#from django.conf.urls.static import static
from blogpage.feeds import LatestEntriesFeed

app_name = 'blogpage'  

urlpatterns = [
    path('', blog_view, name='blog'),
    path('<int:pid>' ,blog_single,name='single'),
    #path('author/<str:author_username>' ,blog_view,name='author'),
    path('author/<str:author_username>/', blog_view, name='author'),
    #path('category/<str:cat_name>' ,blog_view,name='category'),
    path('category/<str:cat_name>/', blog_view, name='category'),
    #path('tag/<str:tag_name>' ,blog_view,name='tag'),
    path('tag/<str:tag_name>/', blog_view, name='tag'),
    path('search/',blog_search,name='search'),
    path('rss/feed/', LatestEntriesFeed()),
] 

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import StaticViewSitemap
from blogpage.sitemaps import BlogSitemap

from debug_toolbar.toolbar import debug_toolbar_urls
import debug_toolbar

from blog.views import *

#app_name = 'mysite'

sitemaps = {
    'static': StaticViewSitemap,
    'blogpage':BlogSitemap
}

urlpatterns = [
    #re_path(r'^.*$', coming_soon),
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),  
    path('blog/', include('blogpage.urls', namespace='blogpage')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    #path('accounts/',include('django.contrib.auth.urls')),
    
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/blog/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()  
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering=['-created_date']
    def __str__(self):
        return self.subject if self.subject else "No subject"
    


class Newsletter(models.Model):
    email = models.EmailField()
    def __str__(self):
        return self.email

    

mysite/blog/forms.py
from django import forms

#from django.forms import ModelForm
from blog.models import Contact,Newsletter
from captcha.fields import CaptchaField


class NameForm(forms.Form):
    name = forms.CharField(label='name', max_length=100)
    email = forms.EmailField(label='email')
    subject = forms.CharField(label='subject',max_length=100)
    message = forms.CharField(widget=forms.Textarea)



class Contactform(forms.ModelForm):
    #subject = forms.CharField(required=False)
    captcha = CaptchaField()
    class Meta:
        model=Contact
        fields ='__all__'


class Newsletterform(forms.ModelForm):
    class Meta:
        model=Newsletter
        fields ='__all__'

mysite/blog/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from blog.models import *
from blog.forms import Newsletterform,Contactform
from blogpage.models import *
from django.contrib import messages

from django.http import HttpResponse


# Create your views here.

def index_view(request):
    posts=Post.objects.all()
    context={"posts":posts}
    return render(request,'website/index.html',context)
    #return render(request,'website/index.html')


def about_view(request):
    return render(request,'website/about.html')

def contact_view(request):
    if request.method == 'POST':
        form = Contactform(request.POST)
        print('====================post===================================')
        if form.is_valid():
            form.instance.name="Unknown"
            form.save()
            messages.add_message(request, messages.SUCCESS, "Form saved successfully.")
        else:
            messages.error(request, 'The form was not saved successfully.!')
            print('===================The form was not saved successfully============================')

    form = Contactform()
    return render(request,'website/contact.html',{"form": form})
'''
def contact_view(request):
    if request.method == 'POST':
        print('Name : ')
        #print('Email : ',request.POST.get('email'))
    else:
        print("GET")
    form = Contactform()
    return render(request,'website/contact.html',{"form": form})
'''
#======================================================================

def elements_view(request):
    return render(request,'elements.html')


def newsletters_view(request):
    if request.method == 'POST':
        form= Newsletterform(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')


def test(request):
    tmp_dict={}
    if request.method == 'POST':
        form = Contactform(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Form saved successfully. !')
        else:
            return HttpResponse('The form was not saved successfully.!')

    form = Contactform()
    return render(request,'test.html',{"form": form})



#def coming_soon(request):
    #return HttpResponse("<h1 style='text-align:center; margin-top:50px;'>به زودی در دسترس خواهد بود</h1>")


def coming_soon(request):
    html = """
    <!DOCTYPE html>
    <html lang="fa">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="این وبسایت به زودی در دسترس خواهد بود.">
        <meta name="keywords" content="وبلاگ, سایت در دست ساخت, به زودی">
        <meta name="author" content="Hossein Ghorbanzadeh">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>به زودی در دسترس خواهد بود</title>
    </head>
    <body>
        <h1 style='text-align:center; margin-top:50px;'>به زودی در دسترس خواهد بود</h1>
    </body>
    </html>
    """
    return HttpResponse(html)

mysite/templates/blog/blog-home.html
{% extends 'website/base_blog.html' %}


{% load static %}
{% block content %} 

<body class="blog-page">
  <main class="main">

    <!-- Page Title -->
    <div class="page-title">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Blog</h1>
              <p class="mb-0">
                This single page contain several different topics.
               
                </p>
            </div>
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li>
              <a href="{% url 'blog:index' %}">
                Home
              </a>
            </li>
            <li class="current">Blog</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Page Title -->

    <!-- Blog Posts Section -->
    
    <section id="blog-posts" class="blog-posts section">
      <div class="container">
    
        <div class="row gy-4">
          {% for post in posts %}
            <div class="col-lg-4">
              <article class="blog-post">
    
                <!-- تصویر پست -->
                <div class="post-img">
                  <img src="{{ post.image.url }}" alt="" class="img-fluid">
                </div>
    
                <!-- دسته‌بندی‌ها -->
                <div class="post-categories mb-2">
                  {% for cat in post.category.all %}
                    <a href="{% url 'blogpage:category' cat_name=cat.name %}" class="badge bg-primary me-1">
                      {{ cat.name }}
                    </a>
                  {% endfor %}
                </div>
    
                <!-- عنوان یا خلاصه محتوا -->
                <h2 class="title">
                  
                  <a href="{% url 'blogpage:single'  pid=post.id %}">
                    {{ post.title }}
                  </a>
                  <br>

                  <a href="{% url 'blogpage:single'  pid=post.id %}">
                    {{ post.content|striptags|truncatewords:10|safe }}
                  </a>
                </h2>
    
                <!-- اطلاعات نویسنده و تاریخ -->
                <div class="d-flex align-items-center mt-3">
                  <img src="{% static 'img/blog/blog-author.jpg' %}" alt="" class="img-fluid post-author-img flex-shrink-0 rounded-circle me-2" width="40" height="40">
                  <div class="post-meta">
                    <p class="post-author mb-0 fw-bold">{{ post.author }}</p>
                    <p class="post-date mb-0 text-muted">{{ post.published_date|date:"D d M Y" }}</p>
                  </div>
                </div>
    
              </article>
            </div>
          {% endfor %}
        </div>
    
        <!-- صفحه‌بندی -->
        {% if posts.has_other_pages %}
        <nav class="mt-5 d-flex justify-content-center">
          <ul class="pagination">
            {% if posts.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1">&laquo;</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">Before</a>
              </li>
            {% endif %}
    
            {% for num in posts.paginator.page_range %}
              {% if posts.number == num %}
                <li class="page-item active">
                  <span class="page-link">{{ num }}</span>
                </li>
              {% elif num >= posts.number|add:"-2" and num <= posts.number|add:"2" %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
              {% endif %}
            {% endfor %}
    
            {% if posts.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ posts.paginator.num_pages }}">&raquo;</a>
              </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
    
      </div>
    </section>
    

    <!-- Blog Pagination Section -->


  </main>

  {% endblock%}

mysite/templates/blog/blog-home1.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{%block body %}
			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
									<li>
										{% for cat in post.category.all %} 
										<a href="{% url 'blogpage:category' cat_name=cat.name %}">{{cat.name}}</a>
										{% if not forloop.last %}
										
										{% endif %}
										{% endfor %}
									</li>
									</ul>
									
									<div class="user-details row">
										
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blogpage:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% comments_count post.id %} Comments</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
										
									</div>
									<a class="posts-title" href="{% url 'blogpage:single'  pid=post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										<!--{{post.content|truncatechars:100}}-->
										{{ post.content|truncatewords:20|safe }}
										
										
									</p>
									<a href="{% url 'blogpage:single'  pid=post.id %}" class="primary-btn">View More</a>
								</div>
							</div>
							{% endfor %}	
								
		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">

									{% if posts.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}


									{% for i in posts.paginator.page_range %}
										{% if posts.number == i %}
											<li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
										{% else %}
		                            	<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
										{% endif %}
									{% endfor %}


									{% if posts.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}


		                        </ul>
		                    </nav>
							
							
							
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								{% include 'blog/search.html' %}

								{% include 'blog/blog-writer.html' %}
								{% popularposts 3 %}
								{% include 'blog/blog-ads.html' %}

								{% categorypost %}
								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								<div class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										{% for tag in all_tags %}
										<li><a href="{% url 'blogpage:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
										{% empty %}
										<li>No tags yet.</li>
										{% endfor %}
									</ul>
								</div>								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			

		</body>
		{% endblock %}

mysite/templates/blog/blog-single1.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{%block body %}
		  
			<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{post.title}}				
							</h1>	
							<p class="text-white link-nav"><a href="{%url 'blog:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{%url 'blogpage:blog' %}">Blog </a> <span class="lnr lnr-arrow-right"></span>  {{post.title}} </p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>									
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										<li>
											{% for cat in post.category.all %} 
											<a href="{% url 'blogpage:category' cat_name=cat.name %}">{{cat.name}}</a>
											{% if not forloop.last %}
											,
											{% endif %}
											{% endfor %}
										</li>
										
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blogpage:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views }} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{post.title}}</h3>
									<p class="excert">
										{{ post.content|safe }}
									</p>
								</div>
							</div>
							<div class="navigation-area">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										{% if next_post.id is not none %} 
										<div class="thumb">
											
											<a href="{% url 'blogpage:single'  pid=next_post.id %}"><img class="img-fluid" src="{{next_post.image.url}}" alt=""></a>
											
										</div>
										<div class="arrow">
											
											<a href="{% url 'blogpage:single'  pid=next_post.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
											
										</div>
										<div class="detials">
											<p>Prev Post</p>
											
											<a href="{% url 'blogpage:single'  pid=next_post.id %}"><h4>{{next_post.title}}</h4></a>
											
										</div>
										{% endif %}
									</div>
									{% if prev_post.id is not none %} 
									<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										<div class="detials">
											<p>Next Post</p>
											
											<a href="{% url 'blogpage:single'  pid=prev_post.id %}"><h4>{{prev_post.title}}</h4></a>
											
										</div>
										<div class="arrow">
											
											<a href="{% url 'blogpage:single'  pid=prev_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
											
										</div>
										<div class="thumb">
											
											<a href="{% url 'blogpage:single'  pid=prev_post.id %}"><img class="img-fluid" src="{{prev_post.image.url}}" alt=""></a>
											
										</div>
																	
									</div>	
									{% endif %}								
								</div>
							</div>
							<div class="comments-area">
								<h4>{{comments|length}} Comments</h4>
								{% for comment in comments %}
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c1.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{comment.name}}</a></h5>
                                                <p class="date">{{comment.created_date|naturalday}} </p>
                                                <p class="comment">
                                                    {{comment.message}}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
								{% empty %}	
								<p> No Comments </p>
								{% endfor %}                                       				
							</div>
							<div class="comment-form">
								<h4>Leave a Comment</h4>
								<form method="post" action="{% url 'blogpage:single' pid=post.id %}">
									{% csrf_token %}
									<input type="hidden" name="post" value={{post.id}}>
									{% if request.user.is_authenticated %}
									<div class="form-group form-inline">
										<div class="form-group col-lg-6 col-md-12 name">
											<input  type="hidden" name="name" value={{request.user.first_name}} readonly>
										</div>
										<div class="form-group col-lg-6 col-md-12 email">
											<input  type="hidden" name="email"   value={{request.user.email}} readonly>
										</div>										
									  </div>
									{% else %}
									<div class="form-group form-inline">
									  <div class="form-group col-lg-6 col-md-12 name">
										
									    <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>										
									</div>
									{% endif %}
									<div class="form-group">
										<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									</div>
									<div class="form-group">
										<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									</div>
									
									<button type="submit" class="primary-btn text-uppercase">Post Comment</button>	
								</form>
							</div>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">

								{% include 'blog/search.html' %}
								
								<div class="single-sidebar-widget user-info-widget">
									<img src="{% static 'img/blog/user-info.png' %}" alt="">
									<a href="#"><h4>Charlie Barber</h4></a>
									<p>
										Senior blog writer
									</p>
									<ul class="social-links">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-github"></i></a></li>
										<li><a href="#"><i class="fa fa-behance"></i></a></li>
									</ul>
									<p>
										Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
									</p>
								</div>
								
								{% popularposts 3 %}
								{% include 'blog/blog-ads.html' %}
								{% categorypost %}
							
								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								<div class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										{% for tag in post.tags.all %}
										<li><a href="{% url 'blogpage:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
										{% endfor %}

									</ul>
								</div>								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			


		</body>
		{% endblock %}

mysite/templates/blog/last_post_index.html
{% load blog_tags %}
{% load static %}
	
<section class="recent-blog-area section-gap">
    <div class="container">

        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-60 col-lg-9">
                <div class="title text-center">
                    <h1 class="mb-10">Latest from Our Blog</h1>
                    <p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as has.</p>
                </div>
            </div>
        </div>	

        
        
        <div class="row">
            <div class="active-recent-blog-carusel">

                {% for post in posts %}
                <div class="single-recent-blog-post item">
                    <div class="thumb">
                        <img class="img-fluid" src="{{post.image.url}}" alt="">
                    </div>
                    <div class="details">
                        <div class="tags">
                            <ul>
                                {% for cat in post.category.all %}
                                <li>
                                    <a href="{% url 'blogpage:category' cat_name=cat.name %}">{{cat.name}}</a>
                                </li>
                                {% endfor %}
                               											
                            </ul>
                        </div>
                        <a href="{% url 'blogpage:single'  pid=post.id %}"><h4 class="title">{{post.title}}</h4></a>
                        <p>
                            {{ post.content|truncatewords:10|safe }}
                        </p>
                        <h6 class="date">{{post.created_date}}</h6>
                    </div>	
                </div>
                {% endfor %}


               
                                                                

            </div>
        </div>
        
        
    </div>	
</section>